logging:
  config: classpath:log4j2.xml
---
spring:
  profiles: dev
logging:
  level:
    ROOT: warn
    com.isf: debug
---
spring:
  profiles: prod
logging:
  level:
    ROOT: warn
    com.isf: info
