logging.config: classpath:logback-spring.xml
---
spring:
  profiles: dev
logging:
  level:
    ROOT: info
    com.isf: debug
---
spring:
  profiles: prod
logging:
  level:
    ROOT: warn
    com.isf: info